image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .cargo
    - target/

before_script:
  - rustup component add rustfmt

stages:
  - lint
  - test
  - build
  - package
  - verify

lint:fmt:
  stage: lint
  cache: {}
  script:
    - cargo fmt -- --check

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test

build:release:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/monk
      - target/release/monkd
  only:
    refs:
      - master

package-deb:
  stage: package
  before_script:
    - cargo install cargo-deb
  script:
    - cargo deb -p monk-cli
    - cargo deb -p monkd
  artifacts:
    paths:
      - target/debian
  only:
    refs:
      - master

package-fedora:
  image: "fedora:latest"
  stage: package
  before_script:
    - until dnf install -y rpmdevtools
    - do
    -    echo "Trying again"
    - done
  script:
    - rpmdev-setuptree
    - mkdir -p ~/rpmbuild/BUILD/target/release
    - cp target/release/monk ~/rpmbuild/BUILD/target/release
    - cp target/release/monkd ~/rpmbuild/BUILD/target/release
    - rpmbuild -ba monk.spec
    - cp ~/rpmbuild/RPMS/x86_64/*.rpm target/
    - ls target/
  artifacts:
    paths:
      - target/*.rpm
  only:
    refs:
      - master

verify-deb:
  image: "ubuntu:latest"
  cache: {}
  stage: verify
  before_script:
    - apt update
    - apt install -y libssl-dev
  script:
    - "dpkg -i target/debian/monk*.deb"
    - monk config
  dependencies:
    - package-deb
  needs: ["package-deb"]
  only:
    refs:
      - master

verify-fedora:
  image: "fedora:latest"
  cache: {}
  stage: verify
  before_script:
    - dnf install -y openssl
  script:
    - ls target/
    - rpm -i target/*.rpm
    - monk config
  dependencies:
    - package-fedora
  needs: ["package-fedora"]
  only:
    refs:
      - master
