image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - rustup component add rustfmt

stages:
  - lint
  - test
  - build
  - package

lint:fmt:
  stage: lint
  script:
    - cargo fmt -- --check

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test

build:release:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release
  # only:
  #   refs:
  #     - master

package:deb:
  stage: package
  before_script:
    - cargo install cargo-deb
  script:
    - cargo deb -p monk-cli
    - cargo deb -p monkd
  artifacts:
    paths:
      - target/debian
  # only:
  #   refs:
  #     - master

cache:
  paths:
    - .cargo
    - target/
