[package]
name = "monk-server"
version = "0.1.0"
authors = ["Fisher Darling <fdarlingco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "*"
tracing-subscriber = "*"
matrix-sdk = { git="https://github.com/matrix-org/matrix-rust-sdk.git", features = ["encryption", "sled_cryptostore"] }
dirs = "3.0.2"
tokio = { version = "^1.6", features= ["full"] }
anyhow = "1.0.40"