[package]
name = "monk-cli"
version = "0.1.0"
authors = ["Fisher Darling <fdarlingco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "monk"
path = "src/bin/monk.rs"

[dependencies]
structopt = "*"
tantivy = "*"
anyhow = "*"
thiserror = "*"
failure = "*"
colored = "*"
monkd = { path = "../monkd" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "*"
config = "*"
reqwest = { version = "*", features = ["json"] }
tokio = "*"
url = "*"
sysinfo = "*"
term-table = "*"
open = "1"