[package]
name = "monkd"
version = "0.1.0"
authors = ["Fisher Darling <fdarlingco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "monkd"
path = "./src/bin/monkd.rs"

[dependencies]
# crossbeam-channel = "*"
tokio = { version = "*", features = ["full"] }
futures = "*"
url =   { version = "*", features = ["serde"] }
chrono = { version = "*", features = ["serde"] }
anyhow = "*"
thiserror = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
rand = "0.7.3"
tracing = "*"
tracing-subscriber = { version = "*", default-features = false, features = ["fmt", "parking_lot"] }
tracing-futures = "*"
tracing-appender = "*"
config = "*"
structopt = "*"
warp = "*"
tantivy = { git = "https://github.com/tantivy-search/tantivy.git" }
monolith = { path = "../monolith" }
reqwest = "*"
directories-next = "*"